/**
 * Better Auth API route handler for Next.js App Router.
 *
 * This file is generated by `create-next-auth-starter` and should
 * not be modified unless you need custom middleware.
 *
 * @example
 * ```
 * GET /api/auth/session
 * POST /api/auth/sign-in/email
 * POST /api/auth/sign-up/email
 * ```
 */
import { toNextJsHandler } from "better-auth/next-js";
import { auth } from "@/auth/server";

export const { GET, POST } = toNextJsHandler(auth.handler);
